### ISSUE TITLE
Module 'kenlm' has no attribute 'Model'

### ISSUE THREAD

**Issue by Tsukimy** [kpu/kenlm#298]
Hi. I wanted to try lm-model in debug, the script was running before. Now I have this error below.

Traceback (most recent call last):
  File "kenlm.py", line 20, in <module>
    import kenlm
  File "...kenlm.py", line 28, in <module>
    lm = kenlm.Model("...zadolbali.arpa")
AttributeError: module 'kenlm' has no attribute 'Model'

What could be wrong? The source of kenlm is from this repo

**Comment by Tsukimy** [comment]
My mistake naming the script
