### ISSUE TITLE
i am beginar to use this can you explain why this happens

### ISSUE THREAD

**Issue by jawahar247** [kpu/kenlm#362]
Reading /home/jawahar/Desktop/jawahar.tmp.arpa
----5---10---15---20---25---30---35---40---45---50---55---60---65---70---75---80---85---90---95--100
****************************************************************************************************
/home/jawahar/Desktop/jawahar/kenlm/util/file.cc:86 in int util::CreateOrThrow(const char*) threw ErrnoException because `-1 == (ret = open(name, 0100 | 01000 | 02, 0400 | 0200 | (0400 >> 3) | ((0400 >> 3) >> 3)))'.
Is a directory while creating /home/jawahar/Desktop/jawahar Byte: 67
ERROR
Traceback (most recent call last):
  File "train_kenlm.py", line 164, in <module>
    main()
  File "train_kenlm.py", line 155, in main
    raise RuntimeError("Training KenLM was not successful!")
RuntimeError: Training KenLM was not successful!

**Comment by marziye-A** [comment]
did you find the answer? its my question too.
